improve based on github.com/blablacar/dgr#215

diff --git a/gomake b/gomake
--- a/gomake
+++ b/gomake
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e
+set -efo pipefail # TODO u
 
  : ${target_name:=dist}
  : ${work_path:=.}
@@ -82,7 +82,7 @@ clean() {
 }
 
 build() {
-    start=`date +%s`
+    start=$(date +%s)
 
     [ -z "$1" ] || osarchi="$1"
     [ ! -z ${version+x} ] || version="0"
@@ -94,7 +94,7 @@ build() {
     fi
 
     echo_green "Goimports"
-    [ -f ${GOPATH}/bin/goimports ] || go get -u golang.org/x/tools/cmd/goimports
+    command -v goimports || go get -u golang.org/x/tools/cmd/goimports
     goimports -w ${go_files}
 
     echo_green "Format"
@@ -104,7 +104,7 @@ build() {
     go tool fix ${go_files}
 
     if [ "$(ls -A ${work_path}/${target_name}/bindata)" ]; then
-        [ -f ${GOPATH}/bin/go-bindata ] || go get -u github.com/jteeuwen/go-bindata/...
+        command -v go-bindata || go get -u github.com/jteeuwen/go-bindata/...
         go-bindata -nomemcopy -pkg dist -prefix dist/bindata -o ${work_path}/${target_name}/bindata.go ${work_path}/${target_name}/bindata/...
     fi
 
@@ -118,7 +118,7 @@ build() {
 
         if [ ${upx} ]; then
             echo_green "Compressing ${e}"
-            [ -f /usr/bin/upx ] || (echo "upx is required to compress" && exit 1)
+            command -v upx || (echo "upx is required to compress" && exit 1)
             upx ${work_path}/${target_name}/${binaryPath} &> /dev/null
         fi
 
@@ -139,19 +139,19 @@ install() {
 }
 
 quality() {
-    start=`date +%s`
+    start=$(date +%s)
     cd ${work_path}
 
     if [ ${errcheck} == 1 ]; then
         echo_green "Err check"
-        [ -f ${GOPATH}/bin/errcheck ] || go get -u github.com/kisielk/errcheck
+        command -v errcheck || go get -u github.com/kisielk/errcheck
         res=$(errcheck ./... | grep -v 'vendor/' | grep -v 'Close(' | grep -v '_test.go')
         err_count "${res}"
         echo_red "${res}"
     fi
 
     echo_green "Lint"
-    [ -f ${GOPATH}/bin/golint ] || go get -u github.com/golang/lint/golint
+    command -v golint || go get -u github.com/golang/lint/golint
     for i in ${go_files}; do
         golint ${i} | grep -v 'should have comment ' || true
     done
@@ -160,17 +160,17 @@ quality() {
     go tool vet ${go_files} || true
 
     echo_green "Misspell"
-    [ -f ${GOPATH}/bin/misspell ] || go get -u github.com/client9/misspell/cmd/misspell
+    command -v misspell || go get -u github.com/client9/misspell/cmd/misspell
     misspell -source=text ${go_files}
 
     echo_green "Ineffassign"
-    [ -f ${GOPATH}/bin/ineffassign ] || go get -u github.com/gordonklaus/ineffassign
+    command -v ineffassign || go get -u github.com/gordonklaus/ineffassign
     for i in ${go_files}; do
         ineffassign -n ${i} || true
     done
 
     echo_green "Gocyclo"
-    [ -f ${GOPATH}/bin/gocyclo ] || go get -u github.com/fzipp/gocyclo
+    command -v gocyclo || go get -u github.com/fzipp/gocyclo
     gocyclo -over 15 ${go_files} || true
 
     cd -
@@ -206,7 +206,7 @@ require_clean_work_tree() {
 }
 
 release() {
-    start=`date +%s`
+    start=$(date +%s)
     if [ "${repo%%/*}" != "github.com" ]; then
         echo "Push to '${repo%%/*}' not implemented"
         exit 1
@@ -253,7 +253,7 @@ release() {
 }
 
 test() {
-    start=`date +%s`
+    start=$(date +%s)
     echo_green "Testing"
     go test -cover $(go list ${work_path}/... | grep -v vendor/)
 
@@ -267,7 +267,7 @@ test() {
 #########################################
 #########################################
 
-global_start=`date +%s`
+global_start=$(date +%s)
 
 commands=()
 while [ $# -gt 0 ]; do
